Usage of .env file instead of storing username and password in the application
snehalbaghel/badgrclient pull request #4
Opened 2020-09-30 13:14 UTC by nasirhm

We'll be using an `.env` file instead of storing usernames and password in the application itself.

Changes Include:

- Addition of `.env` file in `.gitignore`
- Creation of a `.sample.env` file
- Addition of `python-dotenv==0.14.0` in `requirements.txt`
- BadgrClient now defaults to the data from `.env` file instead of None.

fixes: https://github.com/snehalbaghel/badgrclient/issues/3

2020-09-30 22:57 UTC, snehalbaghel requested changes

2020-09-30 22:57 UTC, snehalbaghel commented on badgrclient/badgrclient.py
> +        password: str = getenv('PASSWORD'),
Maybe this should be done in _get_auth_token(). We should remove the option of providing credentials through init cause we wouldn't want the env to be null for #3.

2020-09-30 22:57 UTC, snehalbaghel commented on badgrclient/badgrclient.py
>          client_id: str = None,
Also just realized this shouldn't be optional can you remove the _None_ while you're at it.

2020-10-07 15:41 UTC, nasirhm commented on badgrclient/badgrclient.py
> +        password: str = getenv('PASSWORD'),
Nice Catch, Moving it to `_get_auth_token` would be a good idea.

2020-10-07 15:55 UTC, nasirhm commented on badgrclient/badgrclient.py
> +        password: str = getenv('PASSWORD'),
Modified, here's the fix :https://github.com/snehalbaghel/badgrclient/pull/4/commits/e1c7aac9a5baf91a8faa2e22f225e5422fa5c0f6

2020-10-18 07:25 UTC, snehalbaghel reviewed
I've added a test to test credentials on the master. Can pull and merge those changes and let the tests run again. We will probably have to configure dotenv for testing.

2021-02-22 16:36 UTC, merged

2021-02-22 16:37 UTC, snehalbaghel commented
Tests are passing so I'll merge this. Thanks, @nasirhm for the PR!